const get = db => key => ({
    text: "SELECT value FROM kv WHERE key LIKE $1",
    values: [key],
})

const set_create = db => (key, value) => ({
    text: "INSERT INTO kv (key, value) VALUES ($1, $2)",
    values: [key, value],
})

const set_update = db => (key, value) => ({
    text: "UPDATE kv SET value = $2 WHERE key = $1",
    values: [key, value],
})

const create_table = db => (pgdb, owner) =>
({
    text: `
    CREATE TABLE kv
    (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       key CHARACTER VARYING(255) NOT NULL UNIQUE, 
       value JSONB
    );

    ALTER TABLE kv OWNER TO postgres;
    `,
    values: [],
})


module.exports = {
    get,
    set_create,
    set_update,
    create_table,     
};

