const get = db => key => ({
    text: "SELECT value FROM kv WHERE key LIKE $1",
    values: [key],
})

const set_create = db => (key, value) => ({
    text: "INSERT INTO kv (key, value) VALUES ($1, $2)",
    values: [key, value],
})

const set_update = db => (key, value) => ({
    text: "UPDATE kv SET value = $2 WHERE key = $1",
    values: [key, value],
})

const create_table = db => (pgdb, owner) =>
({
    text: `
    CREATE TABLE kv
    (
       id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       key character varying(255) NOT NULL UNIQUE, 
       value character varying(255) NOT NULL
    );

    ALTER TABLE kv OWNER TO postgres;
    `,
    values: [],
})


const queries = {
    get,
    set_create,
    set_update,
    create_table,     
};

module.exports = queries;

